- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "DevSecOps with AWS"
    DURATION: "140HRS"
    TRAINER: "Sivakumar Reddy"
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Course is {{COURSE}}, Duration is {{DURATION}}, Trainer is {{TRAINER:}}"