- name: variables
  hosts: local
  connection: local
  vars_files:
  - course_details.yaml
  tasks:
  - name: print variables
    vars:
      COURSE: "Ansible"
    ansible.builtin.debug:
      msg: "Course is {{COURSE}}, Duration is {{DURATION}}, Trainer is {{TRAINER}}"