- name: variables preference
  hosts: local
  connection: local
  # vars:
  #   NAME: "Ansible from PLAY"
  # vars_files:
  #   - course_details.yaml
  # vars_prompt:
  #   - name: NAME
  #     prompt: "Enter your name: "
  #     private: false
  tasks:
  - name: variables preference
    # vars:
    #   NAME: "Ansible from TASK"
    ansible.builtin.debug:
      msg: "Hi {{ NAME }}"


# 1. ARGUMENT
# 2. TASK
# 3. PROMPT
# 4. FILE
# 5. PROMPT
# 6. PLAY
# 7. Inventory
# UNDEFINED