- name: conditions
  hosts: local
  connection: local
  vars:
    IS_LIVE: false
    NUM_SESSIONS: 7
  tasks:
  - name: is live or not
    ansible.builtin.debug:
      msg: "Yes it is live"
    when: IS_LIVE
  - name: number of sessions check
    ansible.builtin.debug:
      msg: "Number of sessions are greater than 5"
    when: NUM_SESSIONS > 5