- name: shell vs command
  hosts: local
  connection: local
  tasks:
    - name: pipe operator
      #ansible.builtin.command: cat /etc/password | grep root
      ansible.builtin.shell: cat /etc/passwd | grep root
      register: user_outputs
    - name: print user_outputs
      ansible.builtin.debug:
        msg: "{{ user_outputs }}"