- name: loops
  hosts: local
  connection: local
  become: true
  tasks:
  - name: loop data
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop:
      - Gowtham
      - Sravanthi
      - Kinnera
  - name: install multiple packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
      - nginx
      - mysql