- name: filters
  hosts: local
  connection: local
  vars:
    topics: linux, shell, ansible, terraform
  tasks:
  - name: print strings
    ansible.builtin.debug:
      msg: "Hi Gowtham, {{ GREETINGS | default('Good Morning!!!') }}"
  - name: convert string to list and print
    ansible.builtin.debug:
      msg: "{{ topics | split(',') }}"