- name: filters
  hosts: local
  connection: local
  vars:
    topics: linux, shell, ansible, terraform
    tagsMap:
      name: "catalogue"
      duration: "140HRS"
      location: "Hyderabad"
    tagsList:
      [
        {
            "key": "name",
            "value": "catalogue"
        },
        {
            "key": "duration",
            "value": "140HRS"
        },
        {
            "key": "location",
            "value": "Hyderabad"
        }
    ]
  tasks:
  - name: print strings
    ansible.builtin.debug:
      msg: "Hi Gowtham, {{ GREETINGS | default('Good Morning!!!') }}"
  - name: convert string to list and print
    ansible.builtin.debug:
      msg: "{{ topics | split(',') }}"
  - name: convert map to list
    ansible.builtin.debug:
      msg: "{{ tagsMap | dict2items }}"
  - name: convert list to dict/map
    ansible.builtin.debug:
      msg: "{{ tagsList | items2dict }}"
  - name: read yaml file into variable
    ansible.builtin.set_fact:
      student_yaml: "{{ lookup('file','students.yaml') | from_yaml}}"
  - name: convert yaml to json
    ansible.builtin.debug:
      msg: "{{ student_yaml | to_json }}"