- name: error handling
  hosts: local
  connection: local
  tasks:
  - name: create user
    ansible.builtin.command: id roboshop
    register: user_output
    ignore_errors: true
  - name: user check user_output
    ansible.builtin.debug:
      msg: "{{ user_output }}"
  - name: creatin user based on output value
    ansible.builtin.command: useradd roboshop
    when: user_output.rc != 0
